name: Deploy django to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY_VDS }}
          script: |
            set -e

            cd /var/www/django26

            git fetch origin
            git reset --hard origin/main

            source venv/bin/activate

            pip install -r requirements.txt

            python manage.py check
            python manage.py migrate --noinput
            python manage.py collectstatic --noinput

            sudo systemctl restart django26

            sudo systemctl is-active django26