name: Deploy to VPS

on:
  push:
    branches:
      - main # ou master selon votre branche par défaut

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /var/www/jmessaho.net
            git pull origin main
            # Commandes spécifiques à Django :
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput
            # Relancer l'application :
            sudo systemctl restart gunicorn
