uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.VDS_PORT }}
        script: |
          cd /var/www/jmessaho.net/django26/
          git config pull.rebase false
          git pull origin main
          source venv/bin/activate
          # pip install -r requirements.txt
          python3 manage.py migrate --noinput
          python3 manage.py collectstatic --noinput
          sudo systemctl restart gunicorn
